### ISSUE TITLE
Release v1 on npm

### ISSUE THREAD

**Issue by amercier** [unravelin/ravelinjs#132]
Hello 👋  would it be possible to release v1 on `npm`, please?

The current page (https://www.npmjs.com/package/ravelinjs) is still version `0.x`:
```
$ npm view ravelinjs versions       
[ '0.0.11', '0.0.12', '0.0.13', '0.1.0' ]
```

**Comment by icio** [comment]
Hi @amercier :wave: v1 sure has gone unpublished onto npm for quite some time since its first release, so thank you for requesting it.

My hesitation to publish v1 so far stems from the bundling system that I introduced in v1. The bundle structure ([which is what produces the various +core/+track/+encrypt combinations of ravelinjs](https://github.com/unravelin/ravelinjs/releases/tag/v1.3.0)) works great for users who don't use tree-shaking in their build system and just want a file to throw in `<script src>`.

For users such as yourself wanting to `npm install ravelinjs`, I'd like to offer the same interface but I only get to choose one entrypoint with [package.json's main](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main). If I point main at the all-in-one bundle [lib/bundle/core+track+encrypt.js](https://github.com/unravelin/ravelinjs/blob/v1/lib/bundle/core%2Btrack%2Bencrypt.js) then I risk bloating the user's webpage. I suppose I'm wondering if tree shaking is going to cut that down.

Do you use a build system that would tree-shake out the bits of the [ravelin-1.3.0-core+track+encrypt+promise.min.js](https://github.com/unravelin/ravelinjs/releases/download/v1.3.0/ravelin-1.3.0-core+track+encrypt+promise.min.js) that you're not using?

**Comment by icio** [comment]
I wonder whether I could create a dist for npm that supports imports such as `require('ravelinjs/core+track+encrypt')` backed by the bundle files :thinking:

**Comment by icio** [comment]
@amercier I've published a beta-tagged [`ravelinjs@v1.3.0`](https://www.npmjs.com/package/ravelinjs/v/1.3.0) to npm, which you can install with `npm install ravelinjs@v1` and use with `require('ravelinjs/core+track')` or one of the other bundles.

I'm currently only publshing un-minified UMD builds of the bundles, rather than modules, so I don't think we yet support `import { Ravelin } from 'ravelinjs/core+track'`. I'll aim to work on this next, but I personally haven't yet used modules much. Do you use them, and will you require them? Would you prefer a minified or unminified file from npm?

**Comment by icio** [comment]
> so I don't think we yet support `import { Ravelin } from 'ravelinjs/core+track'`

Depending on your pre-processor, `import Ravelin from 'ravelinjs/core+track'` should work fine. I'll test this some more.

Originally, I was road-testing this import using Node ESCMAScript modules which aren't particularly reflective of browser pre-processors, in hindsight (and which would require the file extension like `import Ravelin from 'ravelinjs/core+track.js'`).

**Comment by icio** [comment]
Hi @amercier, the latest version on npm is now 1.4.0: https://www.npmjs.com/package/ravelinjs. Hopefully the documentation I've added makes everything clear, but feel free to post more questions here if there's something more I should add, or a use-case I should support.

**Comment by amercier** [comment]
Hi @icio sorry for my late answer. 

> Hi @amercier, the latest version on npm is now 1.4.0

Awesome! Thanks ❤️ 

> Do you use a build system that would tree-shake out the bits of the ravelin-1.3.0-core+track+encrypt+promise.min.js that you're not using?

Yes, I use a webpack-based framework (Nuxt.js) that supports tree-shaking indeed. I'll try to upgrade to version 1.4.0 and check whether the bundle produced come bloated or not. I'll open a separate issue here if there is any trouble.

Thanks for your work!

**Comment by amercier** [comment]
Hello @icio FYI here are my bundle testing results, they look pretty good:

# Before

![image](https://user-images.githubusercontent.com/1246795/135147532-3a14d8a1-82e2-4ccd-a435-0322e3512b7b.png)

# After

## Core+track

![image](https://user-images.githubusercontent.com/1246795/135147743-ed378c68-a73f-431b-aa3c-643994d45329.png)

## Core+track+encrypt

![Screenshot 2021-09-28 at 20 43 35](https://user-images.githubusercontent.com/1246795/135147696-4d510236-de51-4a51-96b3-ff1ae3dd4c56.png)

## Core+track+promise

![image](https://user-images.githubusercontent.com/1246795/135148034-18c53181-c41e-4b45-8954-dbc0540d3132.png)
